// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wtkrarqjbbemvvutgqti.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind0a3JhcnFqYmJlbXZ2dXRncXRpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwOTMxNTQsImV4cCI6MjA3MjY2OTE1NH0.fBJqk64TI6k-CuxKRkfWc6os-Beb72xoB3lswnZNOwQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});